.PHONY: all clean

all: sock hello rand realloc uid sleep time

sock: sock.c
hello: hello.c
rand: rand.c
realloc: realloc.c
uid: uid.c
sleep: sleep.c
time: time.c

clean:
	rm -f sock hello rand realloc uid sleep time
