.PHONY: all clean

all: sock hello rand realloc uid sleep time setstdin_fread setstdin_getc setstdin_read

sock: sock.c
hello: hello.c
rand: rand.c
realloc: realloc.c
uid: uid.c
sleep: sleep.c
time: time.c
setstdin_fread: setstdin_fread.c
setstdin_getc: setstdin_getc.c
setstdin_read: setstdin_read.c

clean:
	rm -f sock hello rand realloc uid sleep time setstdin_fread setstdin_getc setstdin_read
